news/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("news.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/news/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("create", views.create, name="create"),
    path("create_comment/<int:news_id>", views.create_comment, name="create_comment"),
    path("edit_news/<int:news_id>", views.edit_news, name="edit_news"),
    path('bookmarked_news/<int:user_id>', views.bookmarked_news, name='bookmarked_news'),
    path('bookmark_news/<int:news_id>', views.bookmark_news, name='bookmark_news'),
    path("news_detail/<str:slug>", views.news_detail, name="news_detail"),
    path("category_news/<int:id>", views.category_news, name="category_news"),
    path("categories", views.categories, name="categories"),
    path("europe_news", views.europe_news, name="europe_news"),
    path("world_news", views.world_news, name="world_news"),
    path("sport_news", views.sport_news, name="sport_news"),
    path("profile/<int:user_id>", views.profile, name="profile"),
    path('search_news/', views.search_news, name='search_news'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("", views.index, name="index"),
]

news/news/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.template.defaultfilters import truncatechars_html, striptags

from filer.fields.image import FilerImageField


class User(AbstractUser):
    pass


class Category(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class News(models.Model):
    APP_NAME = 'news'

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    category = models.ManyToManyField(Category, verbose_name='Category', related_name='news_category')

    content = models.TextField()

    image = models.ImageField(upload_to='news')

    publication_date = models.DateTimeField(default=timezone.now, db_index=True)
    creation_date = models.DateTimeField(auto_now_add=True, editable=False)
    last_modified = models.DateTimeField(auto_now=True, editable=False)

    bookmarks = models.ManyToManyField(User, blank=True, related_name="news_bookmarks")

    is_active = models.BooleanField()

    is_hot_news = models.BooleanField()

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'
        ordering = '-publication_date',

    def __str__(self):
        return (f"{self.title} - {self.publication_date}")

    def get_absolute_url(self):
        return reverse('news_detail', kwargs={'slug': self.slug}, current_app=self.APP_NAME)

    def get_short_excerpt(self):
        return truncatechars_html(self.content, 200)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.news.title} - {self.comment} - {self.user} - {self.timestamp} "

news/news/forms.py
from django import forms
from django.core.validators import validate_slug


class NewsForm(forms.Form):
    title = forms.CharField(max_length=255)
    slug = forms.SlugField(validators=[validate_slug])
    content = forms.CharField(widget=forms.Textarea())
    image = forms.FileField()
    is_active = forms.BooleanField(required=False)
    is_hot_news = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super(NewsForm, self).__init__(*args, **kwargs)
        if not self.data:
            self.fields.get('image').required = True
        else:
            self.fields.get('image').required = False

news/news/views.py
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.db.models import Max
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .models import User, News, Category, Comment
from .forms import NewsForm


def index(request):
    last_four_hot_news = News.objects.filter(is_hot_news=True).order_by('-last_modified')
    news = News.objects.filter(is_active=True).order_by('-last_modified')
    paginator = Paginator(news, 10)
    news_number = request.GET.get('page')
    page_news = paginator.get_page(news_number)    
    return render(request, "news/index.html", {
        "hot_news": last_four_hot_news[:4],
        "all_news": page_news,
        "categories": Category.objects.all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "news/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "news/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "news/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "news/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "news/register.html")


def europe_news(request):
    hot_news_by_category = News.objects.filter(is_hot_news=True, is_active=True, category__title="Europe").order_by('-last_modified')
    news = News.objects.filter(is_active=True, category__title="Europe").order_by('-last_modified')
    paginator = Paginator(news, 10)
    news_number = request.GET.get('page')
    page_news = paginator.get_page(news_number)  

    return render(request, "news/index.html", {
        "hot_news": hot_news_by_category[:4],
        "all_news": page_news,
        "categories": Category.objects.all()
    })  


def world_news(request):
    hot_news_by_category = News.objects.filter(is_hot_news=True, is_active=True, category__title="World").order_by('-last_modified')
    news = News.objects.filter(is_active=True, category__title="World").order_by('-last_modified')
    paginator = Paginator(news, 10)
    news_number = request.GET.get('page')
    page_news = paginator.get_page(news_number)  

    return render(request, "news/index.html", {
        "hot_news": hot_news_by_category[:4],
        "all_news": page_news,
        "categories": Category.objects.all()
    }) 


def sport_news(request):
    hot_news_by_category = News.objects.filter(is_hot_news=True, is_active=True, category__title="Sport").order_by('-last_modified')
    news = News.objects.filter(is_active=True, category__title="Sport").order_by('-last_modified')
    paginator = Paginator(news, 10)
    news_number = request.GET.get('page')
    page_news = paginator.get_page(news_number)  

    return render(request, "news/index.html", {
        "hot_news": hot_news_by_category[:4],
        "all_news": page_news,
        "categories": Category.objects.all()
    }) 


def category_news(request, id):
    hot_news_by_category = News.objects.filter(is_hot_news=True, is_active=True, category__id=id).order_by('-last_modified')
    news = News.objects.filter(is_active=True, category__id=id).order_by('-last_modified')
    paginator = Paginator(news, 10)
    news_number = request.GET.get('page')
    page_news = paginator.get_page(news_number)  

    return render(request, "news/index.html", {
        "hot_news": hot_news_by_category[:4],
        "all_news": page_news,
        "categories": Category.objects.all()
    })    


def categories(request):
    return render(request, "news/categories.html", { "categories": Category.objects.all() })


def news_detail(request, slug):
    user = request.user
    news = News.objects.get(slug=slug)
    return render(request, "news/news_detail.html", {
        "news": news,
        "categories": Category.objects.filter(news_category=news.id),
        "comments": Comment.objects.filter(news=news.id),
        "owner": news.user == user
    })    


@login_required(login_url='/login')
def create(request):
    if request.method == "POST":
        form = NewsForm(request.POST, request.FILES or None)
        if form.is_valid():
            news = News.objects.create(user=request.user,
                                       title=form.cleaned_data["title"],
                                       content=form.cleaned_data["content"],
                                       slug=form.cleaned_data["slug"],
                                       image=form.cleaned_data["image"],
                                       is_active=form.cleaned_data["is_active"],
                                       is_hot_news=form.cleaned_data["is_hot_news"])
            categories_ids = dict(request.POST)['categories']
            news.category.add(*categories_ids)
    
        return HttpResponseRedirect(reverse('index'))

    else:
        form = NewsForm()
        return render(request, "news/create.html", {
            "form": form,
            "categories": Category.objects.all()
        })


@login_required(login_url='/login')
def edit_news(request, news_id):
    news = get_object_or_404(News, id=news_id)
    if request.method == 'POST':
        form = NewsForm(request.POST, request.FILES or None)
        if form.is_valid():
            news.title = form.cleaned_data["title"]
            news.content = form.cleaned_data["content"]
            news.slug = form.cleaned_data["slug"]
            news.is_active = form.cleaned_data["is_active"]
            news.is_hot_news = form.cleaned_data["is_hot_news"]
            if form.cleaned_data["image"]:
                news.image = form.cleaned_data["image"]
            categories_ids = dict(request.POST)['categories']
            news.category.clear()
            news.category.add(*categories_ids)
            news.save()
            return HttpResponseRedirect(reverse('news_detail', kwargs={'slug': news.slug}))
    else:
        return render(request, "news/edit_news.html", { 
            "news": news,
            "categories": Category.objects.all()
        })


def edit(request, title):
    if request.method == 'POST':
            title = request.POST.get('title')
            content = request.POST.get('content')
            util.save_entry(title, content)
            return render(request, "encyclopedia/detail.html", {
                "content": content, "title": title
            })
    else:
        return render(request, "encyclopedia/edit.html", {
            "content": util.get_entry(title), "title": title
        })


@require_POST
@login_required(login_url='/login')
def create_comment(request, news_id):
    user = request.user
    news = News.objects.get(id=news_id)
    comment = request.POST["comment"]
    if comment:
        Comment.objects.create(user=user, news=news, comment=comment)
    return HttpResponseRedirect(reverse('news_detail', kwargs={'slug': news.slug}))


@login_required(login_url='/login')
def bookmark_news(request, news_id):
    user = request.user
    current_news = News.objects.get(id=news_id)
    if current_news.bookmarks.filter(id=user.id).exists():
        current_news.bookmarks.remove(user)
        return JsonResponse({'bookmarked': False, "status": 201})
    else:
        current_news.bookmarks.add(user)
        return JsonResponse({'bookmarked': True, "status": 201})


@login_required(login_url='/login')
def bookmarked_news(request, user_id):
    b_user = get_object_or_404(User, id=user_id)
    bookmarked_news = b_user.news_bookmarks.all().order_by('-last_modified')
    paginator = Paginator(bookmarked_news, 10)
    news_number = request.GET.get('page')
    page_news = paginator.get_page(news_number)    
    return render(request, "news/bookmarked_news.html", { "all_news": page_news, "categories": Category.objects.all() })    


def profile(request, user_id):
    p_user = get_object_or_404(User, id=user_id)
    news = News.objects.filter(user=p_user).order_by('-last_modified')
    paginator = Paginator(news, 10)
    page_number = request.GET.get('page')
    page_news = paginator.get_page(page_number)
    context = {
        'profile_user': p_user,
        'all_news': page_news
    }
    return render(request, "news/profile.html", context)


def search_news(request):
    query = request.GET.get('q')
    results = News.objects.filter(Q(title__icontains=query) | Q(content__icontains=query)).order_by('-last_modified')
    paginator = Paginator(results, 10)
    news_number = request.GET.get('page')
    page_news = paginator.get_page(news_number)      
    return render(request, "news/index.html", {

news/news/templates/news/bookmarked_news.html
{% extends "news/layout.html" %}
{% load static %}

{% block body %}
{% include 'news/news_list.html' %}
{% endblock %}

news/news/templates/news/carousel.html
{% if hot_news %}
<h5 style="text-align: center;">HOT NEWS</h5>
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for news in hot_news %}
    <li data-target="#carouselExampleCaptions" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
    {% endfor %}
  </ol>
  <div class="carousel-inner">
  {% for news in hot_news %}
    <div class="carousel-item {% if forloop.first %}active{% endif %}">
      <a href="{% url 'news_detail' news.slug %}" ><img src="{{ news.image.url }}" class="d-block w-100" alt="{{ news.title }}" style="width:100%"></a>
      <div class="carousel-caption d-none d-md-block">
        <br>
        <a class="newsTitle" href="{% url 'news_detail' news.slug %}" ><h5>{{ news.title }}</h5></a>
        <p>{{ news.get_short_excerpt }}</p>
      </div>
    </div>
  {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endif %}
<script>
  $('#carouselExampleCaptions').carousel({
    interval: 2000
  })
</script>

news/news/templates/news/categories.html
{% extends "news/layout.html" %}

{% block body %}
<h3>All categories:</h3>
{% if categories %}
    {% for category in categories %}
        <div class="item">
            <table class="newsTable">
                <tbody>
                    <tr>
                        <td style="width:100%;">
                            <a href="{% url 'category_news' category.pk %}" >{{ category.title|title }}</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    {% endfor %}
{% else %}
    <div>No categories</div>
{% endif %}
{% endblock %}

news/news/templates/news/create.html
{% extends "news/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<h3>Create News</h3>
<form enctype="multipart/form-data" action="{% url 'create' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group"> 
        <label for="categories" class="requiredField">Category<span class="asteriskField">*</span> </label> 
        <div>
            <select name="categories" required multiple>
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category }}</option>
                {% endfor %}
            </select>
        </div> 
    </div>
    <br><br>
    <input type="submit" class="btn btn-primary">
</form>
{% endblock %}

news/news/templates/news/edit_news.html
  
{% extends "news/layout.html" %}

{% block body %}
    <h3>Edit news:</h3>
    <div class="form">
        <form enctype="multipart/form-data" id="createEntry" action="{% url 'edit_news' news.id %}" method="POST">
            {% csrf_token %}
            <div id="div_id_title" class="form-group"> <label for="id_title" class=" requiredField">Title<span class="asteriskField">*</span> </label>
                <div class=""><input type="text" name="title" maxlength="255" required class="textinput textInput form-control" id="id_title" value="{{news.title}}"> </div>
            </div>
            <div id="div_id_slug" class="form-group"> <label for="id_slug" class=" requiredField">Slug
                <span class="asteriskField">*</span></label><div ><input type="text" name="slug" class="textinput textInput form-control" required id="id_slug" value="{{news.slug}}"> </div>
            </div>
            <div id="div_id_content" class="form-group"> <label for="id_content" class=" requiredField">Content
                <span class="asteriskField">*</span></label><div><textarea name="content" cols="40" rows="10" class="textarea form-control" required id="id_content">{{news.content}}</textarea> </div>
            </div>
            <div id="div_id_image" class="form-group"> <label for="id_image" class=" requiredField">Image</label>
                <p class="file-upload">Currently: <a href="/media/news/210312072040-01-astrazeneca-covid-19-vaccine-italy-0308-large-tease.jpg">{{news.image.url}}</a><br>
                <div><input type="file" name="image" class="clearablefileinput form-control-file" id="id_image"> </div>
            </div>

            <div class="form-group">
                <div id="div_id_is_active" class="form-check">
                    <input type="checkbox" name="is_active" class="checkboxinput form-check-input" id="id_is_active" {% if news.is_active %}checked{% endif %}>
                    <label for="id_is_active" class="form-check-label">Is active</label>
                </div>
            </div>
            <div class="form-group">
                <div id="div_id_is_hot_news" class="form-check">
                    <input type="checkbox" name="is_hot_news" class="checkboxinput form-check-input" id="id_is_hot_news" {% if news.is_hot_news %}checked{% endif %}>
                    <label for="id_is_hot_news" class="form-check-label">Is hot news</label>
                </div>
            </div>
            <div class="form-group"> 
                <label for="categories" class="requiredField">Category<span class="asteriskField">*</span> </label> 
                <div>
                    <select name="categories" required multiple>
                        {% for category in categories %}
                            <option value="{{ category.id }}" {% for n_category in news.category.all %}{% if n_category.id == category.id %}selected{% endif %}{% endfor %}>{{ category }}</option>
                        {% endfor %}
                    </select>
                </div> 
            </div>
            <button type="submit" class="btn btn-primary form">Change</button>
        </form>
    </div>
{% endblock %}

news/news/templates/news/index.html
{% extends "news/layout.html" %}
{% load static %}

{% block body %}
{% include 'news/carousel.html' %}
<br>
{% include 'news/news_list.html' %}
{% endblock %}

news/news/templates/news/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}News{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link href="{% static 'news/carousel.css' %}" rel="stylesheet">
        <link href="{% static 'news/styles.css' %}" rel="stylesheet">
        <script src="{% static 'news/main.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light customNav">
        <a href="{% url 'index' %}" class="image"><img src="{% static 'news/images/logo.png' %}" class="image"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'world_news' %}">World</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'europe_news' %}">Europe</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sport_news' %}">Sport</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create' %}">Create News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bookmarked_news' user_id=user.id %}">Bookmarked News</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'categories' %}" id="navbarDropdown" role="button" data-toggle="dropdown" data-hover="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for category in categories %}
                        <a class="dropdown-item" href="{% url 'category_news' category.pk %}">{{ category.title|title }}</a>
                    {% endfor %}
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'search_news' %}">
                {% csrf_token %}
                <div class="row no-gutters">
                    <div class="col">
                        <input class="form-control rounded-3" name="q" type="text" placeholder="Search News" value="{{query}}" >
                    </div>
                    <div class="col-auto">
                        <button class="btn " type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
            <div class="authSection">
                {% if user.is_authenticated %}
                    <strong><div>Signed in as <a href="{% url 'profile' user_id=user.id %}">{{user|title}}</a> | <a href="{% url 'logout' %}">Log Out</a></strong></div>
                {% else %}
                    <div>Not signed in <strong>| <a href="{% url 'login' %}">Log In</a> | <a href="{% url 'register' %}">Register</a></strong></div>
                {% endif %}
            </div>
        </div>
        </nav>
        <br>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

news/news/templates/news/login.html
{% extends "news/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

news/news/templates/news/news_detail.html
{% extends "news/layout.html" %}

{% block body %}
<div class="item">
    <table class="newsTable">
        <tbody>
            <tr>
                <td>
                    <a href="{% url 'news_detail' news.slug %}" ><img src="{{ news.image.url }}" style="width:60%;"/></a>
                </td>
            </tr>        
            <tr>
                <td style="width: 100%;" valign="top">
                    <h5>{{ news.title }}</h5>
                    <br>
                    <div>{{ news.content }}</div>
                </td>
            </tr>
            <tr>
                <td>
                    {% if user.is_authenticated %}<i class="fa {% if news.bookmarks.all.count >= 1 %}fa-bookmark{% else %}fa-bookmark-o{% endif %} bookmarkNews" data-news-id="{{news.id}}" style="cursor: pointer;"></i>{% endif %}
                    <div>By: <a href="{% url 'profile' user_id=news.user.id %}">{{ news.user }}</a></div>
                    <div><i class="fa fa-clock-o" aria-hidden="true"></i> Updated {{ news.last_modified|date:"M d, Y H:i" }}</div>
                    <div>Categories: {% for category in categories %}{{category|title}}{% if not forloop.last %}, {% endif %}{% endfor %}</div>
                    {% if news.user == user %}
                        <br>
                        <a class="edit-post-link btn btn-primary" href="{% url 'edit_news' news.id %}">Edit news</a>
                    {% endif %}                    
                </td>
            </tr>
        </tbody>
    </table>
    {% if user.is_authenticated %}
    <form action="{% url 'create_comment' news.id %}" method="POST">
        {% csrf_token %}
        <label for="comment">Add comment:</label>
        <textarea id="comment" class="form-control" name="comment" rows="4" placeholder="Your Comment"></textarea>
        <input type="submit" class="btn btn-primary" style="display: inline-block; margin-top: 10px;">
    </form>
    {% endif %}
    <hr>
    <h6>Comments</h6>
    {% for comment in comments %}
    <div class="container">
        <div class="card text-left">
            <h6 class="card-header">{{comment.user}}</h6>
            <div class="card-body">
                <p>{{comment.comment}}</p>
                <p>{{comment.timestamp|date:"M d, Y H:i"}}</p>
            </div>
        </div>
    </div>
    <br>
    {% endfor %}
</div>

{% endblock %}

news/news/templates/news/news_list.html
{% if all_news %}
    {% for news in all_news %}
    <div class="item">
        <table class="newsTable">
            <tbody>
                <tr>
                    <td style="width:30%;">
                        <a href="{% url 'news_detail' news.slug %}" ><img src="{{ news.image.url }}" style="width:90%;"/></a>
                    </td>
                    <td style="width: 70%;" valign="top">
                        <a class="newsTitle" href="{% url 'news_detail' news.slug %}" ><h2>{{ news.title }}</h2></a>
                        <h6>By <a href="{% url 'profile' user_id=news.user.id %}">{{news.user|title}}</a></h6>
                        <p>{{ news.get_short_excerpt }}</p>
                        <div><i class="fa fa-clock-o" aria-hidden="true"></i> Updated {{ news.last_modified|date:"M d, Y H:i" }}</div>
                        <br>
                        {% if user.is_authenticated %}<i class="fa {% if news.bookmarks.all.count >= 1 %}fa-bookmark{% else %}fa-bookmark-o{% endif %} bookmarkNews" data-news-id="{{news.id}}" style="cursor: pointer;"></i>{% endif %}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    {% endfor %}
    <br>
    {% if all_news.has_previous %}
        <a class="btn btn-primary" href="?page=1">&laquo; first</a>
        <a class="btn btn-primary" href="?page={{ all_news.previous_page_number }}">previous</a>
    {% endif %}
    <span class="current">
        <strong>Page {{ all_news.number }} of {{ all_news.paginator.num_pages }}</strong>
    </span>
    {%if all_news.has_next %}
        <a class="btn btn-primary" href="?page={{ all_news.next_page_number }}">next</a>
        <a class="btn btn-primary"  href="?page={{ all_news.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
{% else %}
    <div>No news</div>
{% endif %}

news/news/templates/news/profile.html
  
{% extends "news/layout.html" %}

{% block body %}
    <table class="newsTable">
        <tbody>
            <tr>
                <td style="width: 30%;" valign="top">
                    <h3>{{ profile_user.username|title }}</h3>
                </td>
            </tr>
        </tbody>
    </table>
    <hr>
    {% include 'news/news_list.html' %}
{% endblock %}

news/news/templates/news/register.html
{% extends "news/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}